# Permalinks
permalink:      /:year-:month-:day/:title

# Setup
title:          Darcski
paginate:       5
baseurl:        ""
url:            "https://darcski.github.io"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name:         Darcski
  url:          http://darcski.github.io
  email:        noemail@example.com

# Custom vars
version:        3.4.1
github:
  repo:         https://github.com/darcski/darcski.github.io

# Gems
plugins:
  - jekyll-paginate
